
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO qwat_ro;
GRANT SELECT ON public.geometry_columns TO qwat_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA distribution
    GRANT SELECT ON TABLES TO qwat_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO qwat_rw;
GRANT SELECT ON public.geometry_columns TO qwat_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA distribution
    GRANT ALL ON TABLES TO qwat_rw;